SELECT *
FROM 	EMPLOYEES e ;

SELECT 	sum(SALARY), avg(SALARY), min(SALARY), max(SALARY)
FROM 	EMPLOYEES e 
WHERE 	JOB_ID LIKE 'SA%'
;

SELECT 	*
FROM 	DEPARTMENTS d 
;

SELECT 	e.FIRST_NAME ,e.LAST_NAME ,e.DEPARTMENT_ID ,d.DEPARTMENT_NAME 
FROM 	EMPLOYEES e INNER JOIN DEPARTMENTS d 
ON		e.DEPARTMENT_ID = d.DEPARTMENT_ID ;

SELECT 	e.FIRST_NAME ,e.LAST_NAME ,e.DEPARTMENT_ID ,d.DEPARTMENT_NAME, d.LOCATION_ID 
FROM 	EMPLOYEES e FULL OUTER JOIN DEPARTMENTS d 
ON 		e.DEPARTMENT_ID = d.DEPARTMENT_ID 
ORDER BY e.DEPARTMENT_ID 
;

SELECT 	d.DEPARTMENT_ID , d.DEPARTMENT_NAME , d.LOCATION_ID , l.CITY ,l.STREET_ADDRESS ,l.COUNTRY_ID
FROM 	DEPARTMENTS d INNER JOIN LOCATIONS l 
ON 		d.LOCATION_ID = l.LOCATION_ID ;

SELECT 	e.FIRST_NAME||' '||e.LAST_NAME AS name,
		e.DEPARTMENT_ID , 
		d.DEPARTMENT_NAME , 
		l.LOCATION_ID ,
		l.CITY ,
		j.JOB_ID 
FROM 	EMPLOYEES e 
		INNER JOIN  DEPARTMENTS d 
		ON e.DEPARTMENT_ID =d.DEPARTMENT_ID 
		INNER JOIN LOCATIONS l 
		ON d.LOCATION_ID = l.LOCATION_ID
		INNER JOIN JOBS j 
		ON e.JOB_ID = j.JOB_ID 
WHERE 	l.CITY = 'Seattle'
ORDER BY DEPARTMENT_ID 
; 

SELECT 	count(*)
FROM 	EMPLOYEES e 
		INNER JOIN  DEPARTMENTS d 
		ON e.DEPARTMENT_ID =d.DEPARTMENT_ID 
		INNER JOIN LOCATIONS l 
		ON d.LOCATION_ID = l.LOCATION_ID
		INNER JOIN JOBS j 
		ON e.JOB_ID = j.JOB_ID 
WHERE 	l.CITY = 'Seattle'
; 

SELECT 	JOB_ID 
FROM 	EMPLOYEES e
WHERE 	EMPLOYEE_ID =200
; 

SELECT 	job_id
FROM 	JOB_HISTORY jh 
WHERE 	EMPLOYEE_ID =200;

SELECT 	e.FIRST_NAME||' '||e.LAST_NAME AS name,
		jh.START_DATE||'~'||jh.END_DATE AS history 
FROM 	EMPLOYEES e LEFT OUTER JOIN JOB_HISTORY jh 
	ON	e.EMPLOYEE_ID = jh.EMPLOYEE_ID 
ORDER BY history
; 

-- e.job_id = jh.job_id 와 e.employee_id = jh.employee_id 가 같은데 
SELECT 	e.FIRST_NAME ||' '||e.LAST_NAME AS name,
		e.DEPARTMENT_ID ,
		d.DEPARTMENT_NAME 
FROM 	EMPLOYEES e inner JOIN DEPARTMENTS d 
	ON 	e.DEPARTMENT_ID =d.DEPARTMENT_ID 
;

SELECT 	e.FIRST_NAME ||' '||e.LAST_NAME AS name,
		e.DEPARTMENT_ID ,
		d.DEPARTMENT_NAME 
FROM 	EMPLOYEES e LEFT OUTER JOIN DEPARTMENTS d 
	ON 	e.DEPARTMENT_ID =d.DEPARTMENT_ID 
;

SELECT *
FROM EMPLOYEES e 
WHERE FIRST_NAME = 'Kimberely';


