-- 기본키 
CREATE TABLE primary_test(
	studentID	NUMBER(10) PRIMARY KEY,
	name		varchar2(20) 
);

CREATE TABLE primary_test2(
	studentID	NUMBER(10) ,
	name		varchar2(20),
	CONSTRAINTS studentpk PRIMARY KEY (studentid)
);


CREATE TABLE primary_test3(
	studentID	NUMBER(10) ,
	name		varchar2(20)
);
ALTER TABLE PRIMARY_TEST3 ADD CONSTRAINTS studentPK3 PRIMARY KEY (studentid);

-- FK
CREATE TABLE daddy(
	IDX		NUMBER(10),
	mID		NUMBER(10) PRIMARY KEY
);

CREATE TABLE daughter(
	IDX 	NUMBER(10) PRIMARY KEY,
	mID		NUMBER(10),
	CONSTRAINTS fk_da FOREIGN KEY(mid) 
	REFERENCES daddy(mid) ON DELETE CASCADE
);

INSERT INTO daddy VALUES (1,10);
INSERT INTO daddy VALUES (2,20);

INSERT INTO DAUGHTER VALUES (100,10);
INSERT INTO DAUGHTER VALUES (200,20);
INSERT INTO DAUGHTER VALUES (300,20);
INSERT INTO DAUGHTER VALUES (300,30);

SELECT *
FROM DAUGHTER 
;

DELETE FROM DAUGHTER WHERE idx = 100;

DELETE FROM DAddy WHERE idx = 2;

CREATE TABLE daddy2(
	IDX		NUMBER(10),
	mID		NUMBER(10) PRIMARY KEY
);

CREATE TABLE daughter2(
	IDX 	NUMBER(10) PRIMARY KEY,
	mID		NUMBER(10),
	CONSTRAINTS fk_da2 FOREIGN KEY(mid) 
	REFERENCES daddy2(mid) ON DELETE SET NULL
);

INSERT INTO daddy2 VALUES (1,10);
INSERT INTO daddy2 VALUES (2,20);

INSERT INTO DAUGHTER2 VALUES (100,10);
INSERT INTO DAUGHTER2 VALUES (200,20);
INSERT INTO DAUGHTER2 VALUES (300,20);


SELECT *
FROM DAUGHTER2 
;

DELETE FROM DAUGHTER2 WHERE idx = 100;

SELECT *
FROM daddy2
;
DELETE FROM DAddy2 WHERE idx = 2;